# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Githook < Formula
  desc "Webhook router + worker SDK for GitHub, GitLab, Bitbucket. Route events by rules and consume via Watermill."
  homepage "https://github.com/yindia/githook"
  version "0.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yindia/githook/releases/download/v0.0.4/githook_0.0.4_darwin_amd64.tar.gz"
      sha256 "c060fc067732c7b0f0ed85373df9b76be810dc399a02e55d7c3c483820927644"

      def install
        bin.install "githook"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yindia/githook/releases/download/v0.0.4/githook_0.0.4_darwin_arm64.tar.gz"
      sha256 "32c5446e63cce7f0ee23c11359315f6c977dbb7fc671ae702b917badd0c7ca37"

      def install
        bin.install "githook"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yindia/githook/releases/download/v0.0.4/githook_0.0.4_linux_amd64.tar.gz"
      sha256 "6cb47710ea9551eddb568a18ce010ec40182c3113bf5bb5ca02ce06dd4f61245"
      def install
        bin.install "githook"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yindia/githook/releases/download/v0.0.4/githook_0.0.4_linux_arm64.tar.gz"
      sha256 "29e9962650aedecf97e6b216c01a41a7297b44805724782ddb7959b7c9003f01"
      def install
        bin.install "githook"
      end
    end
  end

  test do
    system "#{bin}/githook", "--help"
  end
end
