# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pltf < Formula
  desc "pltf CLI turns Environment and Service YAML into validated Terraform."
  homepage "https://github.com/yindia/pltf"
  version "0.0.5-beta"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yindia/pltf/releases/download/v0.0.5-beta/pltf_0.0.5-beta_darwin_amd64.tar.gz"
      sha256 "afd144045480c7100cb4ad985951df1de5c334b517af28b6ccb71bcab2628b12"

      def install
        bin.install "pltf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yindia/pltf/releases/download/v0.0.5-beta/pltf_0.0.5-beta_darwin_arm64.tar.gz"
      sha256 "7eda343bf5a680fc58b9fdc1527290beaf693f8c76561c133b059757f06d8a75"

      def install
        bin.install "pltf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yindia/pltf/releases/download/v0.0.5-beta/pltf_0.0.5-beta_linux_amd64.tar.gz"
      sha256 "81ab736e7665b39d46dbf3a8db1e5243ecb3a05950c71ea63fa975fa1cbae29f"
      def install
        bin.install "pltf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yindia/pltf/releases/download/v0.0.5-beta/pltf_0.0.5-beta_linux_arm64.tar.gz"
      sha256 "e918d262dd3d6ade2b40ab386b35a16e0a485229ff8efb648734dfa52f6d4860"
      def install
        bin.install "pltf"
      end
    end
  end

  test do
    system "#{bin}/pltf", "--help"
  end
end
