# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rootcause < Formula
  desc "RootCause is a local-first MCP server that helps operators manage Kubernetes resources and identify the real root cause of failures through interoperable toolsets."
  homepage "https://github.com/yindia/rootcause"
  version "0.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yindia/rootcause/releases/download/v0.0.2/rootcause_0.0.2_darwin_amd64.tar.gz"
      sha256 "34a2b7c657eabcca1b976e9045fda323d2d158c39a7b4fc1cc75d08506259337"

      def install
        bin.install "rootcause"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yindia/rootcause/releases/download/v0.0.2/rootcause_0.0.2_darwin_arm64.tar.gz"
      sha256 "5ce5bba3153f0ac5fce80c78cfd8116a2fc2f53e94b8ad61301c9786e7095049"

      def install
        bin.install "rootcause"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yindia/rootcause/releases/download/v0.0.2/rootcause_0.0.2_linux_amd64.tar.gz"
      sha256 "ff229f6ee3f91904438a9076d11ed852347c19f3ba57cf181d8c81f968bbffea"
      def install
        bin.install "rootcause"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yindia/rootcause/releases/download/v0.0.2/rootcause_0.0.2_linux_arm64.tar.gz"
      sha256 "4bf3c186a35fe1a11dd3d2b25587967a5f9ed937c072a6e41eddcf30d3cc8449"
      def install
        bin.install "rootcause"
      end
    end
  end

  test do
    system "#{bin}/rootcause", "--help"
  end
end
