# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rootcause < Formula
  desc "RootCause is a local-first MCP server that helps operators manage Kubernetes resources and identify the real root cause of failures through interoperable toolsets."
  homepage "https://github.com/yindia/rootcause"
  version "0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yindia/rootcause/releases/download/v0.0.3/rootcause_0.0.3_darwin_amd64.tar.gz"
      sha256 "8789ba24bf269af8d0e486427be8de2d41e76504afe9da66ec1a7acf96267aca"

      def install
        bin.install "rootcause"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yindia/rootcause/releases/download/v0.0.3/rootcause_0.0.3_darwin_arm64.tar.gz"
      sha256 "41621a29ce839d83c1900b7bd2a7f2e4a0de52ffd2d9ddd3089e01a78214ce94"

      def install
        bin.install "rootcause"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yindia/rootcause/releases/download/v0.0.3/rootcause_0.0.3_linux_amd64.tar.gz"
      sha256 "17299396ea2b2969eff1b9ea2c7eca5c831e48661007aff20c0d6c39e68bba7a"
      def install
        bin.install "rootcause"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yindia/rootcause/releases/download/v0.0.3/rootcause_0.0.3_linux_arm64.tar.gz"
      sha256 "59920835fd0292bbe2d8a019964cdb5d3958fb791186b6b316c667ff3dd72b61"
      def install
        bin.install "rootcause"
      end
    end
  end

  test do
    system "#{bin}/rootcause", "--help"
  end
end
