# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Snip < Formula
  desc "SNIP: Search, Navigate, Index, Parse"
  homepage "https://github.com/yindia/snip"
  version "0.0.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yindia/snip/releases/download/v0.0.8/snip_0.0.8_darwin_amd64.tar.gz"
      sha256 "09d08e394805d37f836cab90fb6466e205d4a3c32de93ce897aa2bab901105d3"

      def install
        bin.install "snip"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yindia/snip/releases/download/v0.0.8/snip_0.0.8_darwin_arm64.tar.gz"
      sha256 "e1e5d81e339958dca87e6d45b103e2a7a53ac652ced03d21326048079ca05498"

      def install
        bin.install "snip"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yindia/snip/releases/download/v0.0.8/snip_0.0.8_linux_amd64.tar.gz"
      sha256 "ca73e6c929361f10966f5bf7c16a63df8bc7f383e9781aa089f213c42fba4a44"
      def install
        bin.install "snip"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yindia/snip/releases/download/v0.0.8/snip_0.0.8_linux_arm64.tar.gz"
      sha256 "65eb1d2a45cd1d7bb28ec727b0c165eddea64d55e23b57bcbd18df7beefd6787"
      def install
        bin.install "snip"
      end
    end
  end

  test do
    system "#{bin}/snip", "--help"
  end
end
